### ISSUE TITLE
Add a configuration option for the number of VM migration retries

### ISSUE THREAD

**Issue by beloglazov** [beloglazov/openstack-neat#2]
Currently, there is no limit on the VM migration retries. There should be a configuration option specifying the maximum number of allowed retries.

**Comment by ghost** [comment]
hello Mr.Beloglazov
I am trying to install openstack Neat to apply my proposed algorithm.
 I installed the openstack Neat step by step as you mentioned in your thesis and github, everything was ok until the "setup.py installation".
when I run the command:
"sudo python setup.py install"

I confronted to this message:

Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    distribute_setup.use_setuptools()
  File "/home/niloofar/Desktop/openstack-neat-master/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/niloofar/Desktop/openstack-neat-master/distribute_setup.py", line 124, in _do_download
    to_dir, download_delay)
  File "/home/niloofar/Desktop/openstack-neat-master/distribute_setup.py", line 194, in download_setuptools
    src = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required


in your opinion, how can i fix this problem?
